[project]
name = "end-to-end-customer-churn-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "gradio>=6.5.1",
    "great-expectations>=1.11.1",
    "mlflow>=1.27.0",
    "numpy>=2.4.1",
    "optuna>=4.7.0",
    "pandas>=3.0.0",
    "posthog>=7.8.2",
    "protobuf<5.0.0",
    "scikit-learn>=1.8.0",
    "setuptools>=80.10.2",
    "uvicorn>=0.40.0",
    "xgboost>=3.1.3",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
]
